# Generated by Django 4.0.1 on 2022-01-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_id', models.CharField(max_length=18)),
                ('hostname', models.CharField(max_length=14)),
                ('hoopback', models.CharField(max_length=20)),
                ('mac_address', models.CharField(max_length=17)),
            ],
        ),
    ]
