# Generated by Django 4.0.1 on 2022-01-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_alter_routerdetails_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerdetails',
            name='loopback',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
